name: Build-and-Publish

on:
  # triggers on pushes with tag
  push:
    tags:
      - '*.*'

jobs:
  # build the apk for release
  build:
    runs-on: ubuntu-latest
    steps:
      # check out repo with submodules
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: senpai
          submodules: recursive

      # setup jdk 1.8
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      # make gradlew executeable
      - name: Make Gradle Executable
        run: chmod +x ./gradlew
      
      # build using gradle
      - name: Build with Gradle
        run: ./gradlew build
        
      # build apk
      - name: Build Release APK
        run: ./gradlew assembleRelease
      
      # sign APK
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # rename signed apk
      - name: Rename Signed APK
        run: mv ${{ steps.sign_apk.outputs.signedReleaseFile }} ./tenshi-content.apk
      
      # upload artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk-build
          path: ./tenshi-content.apk
      
  # upload the built apk to github release
  upload_github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # download artifact from previous step
      - name: Download APK Artifact
        uses: actions/download-artifact@v2
        with:
          name: apk-build
          path: ./

      # generate apk checksum
      - name: "Generate APK Checksum"
        run: sha256sum ./tenshi-content.apk > tenshi-content.sha256

      # add apk to release
      - name: Add APK to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: automatic build
          files: |
            ./tenshi-content.apk
            ./tenshi-content.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
          